SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/domain/AuditingFields.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/domain/Cart.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/domain/Order.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/domain/OrderDetail.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/domain/Product.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/domain/account/EnterAccount.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/domain/account/UserAccount.java
=> #7 - Spring Entity 설계

SI-Track-Backend/build.gradle, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/repository/ProductRepository.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/repository/UserAccountRepository.java
=> #14 - Querydsl 설정 추가

SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/config/security/JwtProvider.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/config/security/SecurityConfig.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/config/security/auth/PrincipalDetails.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/config/security/auth/PrincipalDetailsService.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/config/security/filter/JwtAuthenticationFilter.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/config/security/filter/JwtAuthorizationFilter.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/controller/AccountController.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/domain/account/UserAccount.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/dto/LoginDto.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/dto/UserAccountDto.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/service/AccountService.java, SI-Track-Backend/src/main/resources/application.yaml
=> #16 - Spring Security를 활용한 로그인 구현

SI-Track-Backend/.gitignore
=> #18 - gitignore 내용 추가

SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/config/security/auth/PrincipalDetails.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/dto/UserAccountDto.java, SI-Track-Backend/src/test/java/com/sitrack/sitrackbackend/service/AccountServiceTest.java
=> #20 - 로그인 관련 테스트 코드 추가

SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/controller/ProductController.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/domain/Cart.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/domain/Category.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/domain/Product.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/domain/Supplier.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/dto/ProductDto.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/service/ProductService.java, SI-Track-Backend/src/main/resources/application.yaml, SI-Track-Backend/src/main/resources/data.sql, SI-Track-Backend/src/test/java/com/sitrack/sitrackbackend/repository/JpaRespositoryTest.java, SI-Track-Backend/src/test/java/com/sitrack/sitrackbackend/repository/ProductRepositoryTest.java, SI-Track-Backend/src/test/java/com/sitrack/sitrackbackend/service/ProductServiceTest.java
=> #22 - product 관련 내용 추가

SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/config/security/auth/PrincipalDetails.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/controller/ProductController.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/dto/ProductDto.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/dto/request/ProductRequest.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/dto/request/ProductUpdateRequest.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/dto/response/ProductResponse.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/service/ProductService.java, SI-Track-Backend/src/test/java/com/sitrack/sitrackbackend/service/ProductServiceTest.java
=> #33 - dto 추가

SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/controller/ProductController.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/domain/Product.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/domain/ProductImage.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/domain/constant/ProductImageType.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/dto/ProductDto.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/dto/ProductImageDto.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/dto/request/ProductRequest.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/repository/ProductImageRepository.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/service/ImageService.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/service/ProductService.java, SI-Track-Backend/src/test/java/com/sitrack/sitrackbackend/service/ProductServiceTest.java
=> #36 - 상품 등록 시 image 추가

SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/controller/ProductController.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/repository/ProductRepository.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/service/PaginationService.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/service/ProductService.java
=> #38 - 페이지 처리 및 검색기능 구현

SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/controller/AccountController.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/controller/ProductController.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/domain/Product.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/domain/ProductImage.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/dto/ProductDto.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/dto/ProductImageDto.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/dto/request/ProductRequest.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/dto/response/ProductResponse.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/repository/ProductImageRepository.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/service/ImageService.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/service/ProductService.java, SI-Track-Backend/src/main/resources/application.yaml, SI-Track-Backend/src/test/java/com/sitrack/sitrackbackend/annotation/WithAuthUser.java, SI-Track-Backend/src/test/java/com/sitrack/sitrackbackend/annotation/WithAuthUserSecurityContextFactory.java, SI-Track-Backend/src/test/java/com/sitrack/sitrackbackend/controller/ProductControllerTest.java, SI-Track-Backend/src/test/java/com/sitrack/sitrackbackend/service/ProductServiceTest.java
=> #40 - 오류, 이미지 코드 수정, 테스트 케이스 추가

Si-Track-Frontend/package-lock.json, Si-Track-Frontend/package.json, Si-Track-Frontend/src/Main.js, Si-Track-Frontend/src/components/Modal.css, Si-Track-Frontend/src/components/Modal.js, Si-Track-Frontend/src/page/Detail.js, Si-Track-Frontend/src/page/Pay.css, Si-Track-Frontend/src/page/Pay.js, Si-Track-Frontend/src/page/Paycomplete.css, Si-Track-Frontend/src/page/Paycomplete.js, Si-Track-Frontend/src/page/Post.js, Si-Track-Frontend/src/page/Register.css, Si-Track-Frontend/src/page/Register.js
결제 화면 view 생성 및 결제 완료, 장바구니 modal창 생성,
다음 주소 검색 api 설정(값을 받아오는 부분에서 문제가 있어서 수정 예정)
상품 등록 화면(Register.js) 이미지 4개 등록 가능하도록 변경
=> #35 - 결제화면 view 생성

SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/config/CorsConfig.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/config/security/SecurityConfig.java
=> #43 - corsFilter 추가

SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/controller/CartController.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/domain/Cart.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/domain/CartItem.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/domain/account/UserAccount.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/dto/request/CartItemRequest.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/dto/response/CartItemResponse.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/repository/CartItemRepository.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/repository/CartRepository.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/service/CartService.java
=> #45 - 장바구니 기능 추가

SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/controller/CartController.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/dto/request/CartItemRequest.java, SI-Track-Backend/src/test/java/com/sitrack/sitrackbackend/controller/CartControllerTest.java, SI-Track-Backend/src/test/java/com/sitrack/sitrackbackend/service/CartServiceTest.java
=> #47 - cart 관련 테스트 코드 추가

Si-Track-Frontend/src/page/Pay.css, Si-Track-Frontend/src/page/Pay.js, Si-Track-Frontend/src/page/Post.js, Si-Track-Frontend/src/page/Signup.js
주소 검색 API value값 가져오도록 코드 수정, 회원가입 페이지에도 적용, css수정
=> #50 - 주소 검색 API 코드 수정

Si-Track-Frontend/src/Main.js, Si-Track-Frontend/src/components/ProductItem.css, Si-Track-Frontend/src/page/Cart.css, Si-Track-Frontend/src/page/Cart.js, Si-Track-Frontend/src/page/Change.css, Si-Track-Frontend/src/page/Change.js, Si-Track-Frontend/src/page/Detail.js, Si-Track-Frontend/src/page/FindId.css, Si-Track-Frontend/src/page/Mypage.css, Si-Track-Frontend/src/page/Pay.css, Si-Track-Frontend/src/page/Pay.js
장바구니 view 생성, 그 외 css 수정 및 link 연결
=> #54 - 장바구니 페이지 생성

SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/config/security/SecurityConfig.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/config/security/auth/PrincipalDetails.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/controller/ProductController.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/domain/account/UserAccount.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/domain/constant/RoleType.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/service/AccountService.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/service/ProductService.java, SI-Track-Backend/src/main/resources/data.sql, SI-Track-Backend/src/test/java/com/sitrack/sitrackbackend/annotation/WithAuthUserSecurityContextFactory.java, SI-Track-Backend/src/test/java/com/sitrack/sitrackbackend/controller/ProductControllerTest.java, SI-Track-Backend/src/test/java/com/sitrack/sitrackbackend/service/ProductServiceTest.java
=> #58 - USER ROLE 추가

SI-Track-Backend/.gitignore, SI-Track-Backend/build.gradle, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/config/EmailConfig.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/config/security/SecurityConfig.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/controller/AccountController.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/dto/MailDto.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/dto/SearchIdDto.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/dto/SearchPwdDto.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/dto/UserAccountInfoDto.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/dto/UserAccountPwdDto.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/dto/response/SearchIdResponse.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/repository/UserAccountRepository.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/service/AccountService.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/service/EmailService.java
=> #60 - User 기능 추가

SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/controller/AccountController.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/service/AccountService.java, SI-Track-Backend/src/test/java/com/sitrack/sitrackbackend/controller/AccountControllerTest.java, SI-Track-Backend/src/test/java/com/sitrack/sitrackbackend/service/AccountServiceTest.java
=> #62 - User Test 추가

SI-Track-Backend/.vscode/settings.json, Si-Track-Frontend/src/page/Login.js, Si-Track-Frontend/src/page/Signup.js
로그인, 회원 가입 페이지에 fetch 코드를 사용하여 통신 및 토큰 부여 완료.
* 백앤드 실행이 안되어서 추후에 고치고 직접 봐야할듯
=> #65 - 로그인 회원가입 fetch 코드 추가

SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/config/security/SecurityConfig.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/controller/ProductController.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/domain/Category.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/domain/Product.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/domain/Supplier.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/dto/AdminProductDto.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/dto/CategoryDto.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/dto/ProductDto.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/dto/SupplierDto.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/dto/request/ProductRequest.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/dto/request/ProductUpdateRequest.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/dto/response/ProductUpdateResponse.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/repository/CategoryRepository.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/repository/SupplierRepository.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/service/AccountService.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/service/AdminService.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/service/ProductService.java, SI-Track-Backend/src/main/resources/data.sql, SI-Track-Backend/src/test/java/com/sitrack/sitrackbackend/controller/AdminControllerTest.java, SI-Track-Backend/src/test/java/com/sitrack/sitrackbackend/controller/ProductControllerTest.java, SI-Track-Backend/src/test/java/com/sitrack/sitrackbackend/repository/ProductRepositoryTest.java, SI-Track-Backend/src/test/java/com/sitrack/sitrackbackend/service/AdminServiceTest.java, SI-Track-Backend/src/test/java/com/sitrack/sitrackbackend/service/CartServiceTest.java, SI-Track-Backend/src/test/java/com/sitrack/sitrackbackend/service/OrderServiceTest.java, SI-Track-Backend/src/test/java/com/sitrack/sitrackbackend/service/ProductServiceTest.java
=> #67 - Supplier, Category 연관관계 매핑

SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/controller/AdminController.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/domain/Category.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/domain/Supplier.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/dto/SupplierDto.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/service/AdminService.java, SI-Track-Backend/src/test/java/com/sitrack/sitrackbackend/controller/AdminControllerTest.java, SI-Track-Backend/src/test/java/com/sitrack/sitrackbackend/service/AdminServiceTest.java
=> #69 - supplier, category 로직추가

SI-Track-Backend/build.gradle, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/controller/AccountController.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/controller/AdminController.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/controller/CartController.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/controller/OrderController.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/controller/ProductController.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/dto/AdminProductDto.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/dto/CategoryDto.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/dto/LoginDto.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/dto/SearchIdDto.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/dto/SearchPwdDto.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/dto/SupplierDto.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/dto/UserAccountDto.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/dto/UserAccountInfoDto.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/dto/UserAccountPwdDto.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/dto/request/CartItemRequest.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/dto/request/OrderRequest.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/dto/request/ProductRequest.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/dto/request/ProductUpdateRequest.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/handler/GlobalExceptionHandler.java, SI-Track-Backend/src/test/java/com/sitrack/sitrackbackend/controller/AccountControllerTest.java
=> #71 - Spring Validation 유효성 검사 추가

SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/Exception/CustomException.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/Exception/ErrorCode.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/Exception/ErrorResponseEntity.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/handler/CustomExceptionHandler.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/service/AccountService.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/service/AdminService.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/service/CartService.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/service/ManagerService.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/service/OrderService.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/service/ProductService.java, SI-Track-Backend/src/test/java/com/sitrack/sitrackbackend/service/AccountServiceTest.java, SI-Track-Backend/src/test/java/com/sitrack/sitrackbackend/service/ProductServiceTest.java
=> #73 - CustomException 추가

SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/config/WebConfig.java
=> #75 - Response 오류 수정

SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/domain/ProductImage.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/dto/response/ProductResponse.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/service/ImageService.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/service/ProductService.java, SI-Track-Backend/src/main/resources/data.sql, SI-Track-Backend/src/test/java/com/sitrack/sitrackbackend/service/ProductServiceTest.java
=> #78 - 테스트 데이터 추가 및 이미지 오류 수정

SI-Track-Backend/build.gradle, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/Exception/ErrorCode.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/config/security/JwtProvider.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/config/security/SecurityConfig.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/config/security/filter/JwtAuthenticationFilter.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/config/security/filter/JwtAuthorizationFilter.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/config/security/filter/JwtExceptionFilter.java
=> #81 - Spring Security 유효성 검증

SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/config/JpaConfig.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/controller/AdminController.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/repository/UserAccountRepositoryCustom.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/service/AdminService.java, SI-Track-Backend/src/test/java/com/sitrack/sitrackbackend/controller/AdminControllerTest.java, SI-Track-Backend/src/test/java/com/sitrack/sitrackbackend/service/AdminServiceTest.java
=> #83 - QueryDsl 활용 검색 기능 추가

SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/controller/AdminController.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/repository/OrderRepositoryCustom.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/repository/ProductRepositoryCustom.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/repository/SupplierRepositoryCustom.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/service/AdminService.java, SI-Track-Backend/src/test/java/com/sitrack/sitrackbackend/controller/AdminControllerTest.java, SI-Track-Backend/src/test/java/com/sitrack/sitrackbackend/repository/ProductRepositoryTest.java, SI-Track-Backend/src/test/java/com/sitrack/sitrackbackend/service/AdminServiceTest.java
=>  #85 - QueryDsl 최적화 및 페이징 기능 추가

SI-Track-Backend/build.gradle, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/Exception/ErrorCode.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/config/RedisConfig.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/config/security/JwtProvider.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/config/security/SecurityConfig.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/config/security/filter/JwtAuthenticationFilter.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/controller/AccountController.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/domain/redis/RefreshToken.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/dto/request/TokenReqeust.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/repository/RefreshTokenRepository.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/service/TokenService.java, SI-Track-Backend/src/main/resources/application.yaml
=> #87 - Redis 활용 RefreshToken 저장

SI-Track-Backend/build.gradle, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/config/SwaggerConfig.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/config/security/SecurityConfig.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/controller/AccountController.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/controller/AdminController.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/controller/CartController.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/controller/ManagerController.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/controller/OrderController.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/controller/ProductController.java, SI-Track-Backend/src/main/resources/application.yaml
=> #91 - Swagger 추가

SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/Exception/ErrorCode.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/controller/ProductController.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/dto/ProductImageDto.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/dto/response/ProductResponse.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/dto/response/ProductUpdateResponse.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/repository/ProductImageRepository.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/service/ImageService.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/service/ProductService.java, Si-Track-Frontend/src/Main.js, Si-Track-Frontend/src/components/ProductItem.js, Si-Track-Frontend/src/page/Detail.js, Si-Track-Frontend/src/page/ProductUpdate.css, Si-Track-Frontend/src/page/ProductUpdate.js, Si-Track-Frontend/src/page/Register.js
=> #99 - Product code update

SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/controller/CartController.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/domain/Product.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/dto/OrderItemListDto.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/dto/response/CartItemResponse.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/dto/response/ProductResponse.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/service/CartService.java, Si-Track-Frontend/package-lock.json, Si-Track-Frontend/package.json, Si-Track-Frontend/src/index.js, Si-Track-Frontend/src/page/Cart.js, Si-Track-Frontend/src/page/Detail.js, Si-Track-Frontend/src/page/Pay.js, Si-Track-Frontend/src/recoil/cartItemsState.js
=> #101 - Cart code update 및 Spring 오류 수정

SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/controller/ProductController.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/domain/Product.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/dto/AdminProductDto.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/dto/response/ProductOne.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/repository/ProductRepository.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/repository/ProductRepositoryCustom.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/repository/UserAccountRepositoryCustom.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/service/AccountService.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/service/AdminService.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/service/ProductService.java
=> #104 - Querydsl 검색 성능 최적화

SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/config/security/JwtProvider.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/config/security/SecurityConfig.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/config/security/auth/PrincipalDetailsService.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/controller/AccountController.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/repository/ProductRepositoryCustom.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/repository/UserAccountRepositoryCustom.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/service/AccountService.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/service/AdminService.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/service/CartService.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/service/ManagerService.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/service/OrderService.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/service/ProductService.java
=> #106 -  Refactoring

SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/domain/Order.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/dto/OrderItemListDto.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/dto/request/OrderRequest.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/repository/CartItemRepositoryCustom.java, SI-Track-Backend/src/main/java/com/sitrack/sitrackbackend/service/OrderService.java, Si-Track-Frontend/src/components/ProductItem.js, Si-Track-Frontend/src/page/Cart.css, Si-Track-Frontend/src/page/Detail.js, Si-Track-Frontend/src/page/Mypage.js, Si-Track-Frontend/src/page/Pay.js
=> #109 - Order 구현 및 Refactoring

Si-Track-Frontend/src/components/CategoryItem.js, Si-Track-Frontend/src/components/SupplierItem.js, Si-Track-Frontend/src/page/Change.css, Si-Track-Frontend/src/page/Supplier.css, Si-Track-Frontend/src/page/Userlist.css
=> #108 - 카테고리 삭제
